import { ToolMeta, ToolType } from '../types';

export const TOOL_METADATA: Record<ToolType, ToolMeta> = {
  compressor: {
    id: 'compressor',
    category: 'image',
    badge: 'Most Popular',
    title: 'Client-Side Image Compressor',
    subtitle: 'Shrink PNG, JPG, and WebP images by up to 90% without quality loss.',
    description: 'Compress single or batch images locally in your browser. Set target file size caps (under 50KB, 100KB, 200KB), fine-tune compression quality, compare side-by-side previews, and download instantly with zero server uploads.',
    iconName: 'Minimize2',
    seoKeyword: 'compress image online free',
    metaTitle: 'Free Image Compressor Online — Compress PNG & JPG Under 100KB | BrowserKit',
    metaDescription: 'Compress images online for free. Reduce PNG, JPG, WebP file sizes by up to 90% in your browser. Target exact KB sizes with zero server uploads.',
    faqs: [
      {
        question: 'Is my data private when compressing images?',
        answer: 'Yes, 100%. Processing runs entirely inside your browser memory using HTML5 Canvas APIs. Your images are never uploaded to any remote server.',
      },
    ],
  },
  converter: {
    id: 'converter',
    category: 'image',
    badge: 'High Speed',
    title: 'Universal Image Format Converter',
    subtitle: 'Convert between HEIC, PNG, JPG, WebP, GIF, BMP, and SVG formats.',
    description: 'Batch convert iPhone HEIC photos, modern WebP graphics, vector SVGs, and PNG/JPG photos. Preserves EXIF metadata, original dimensions, and transparency channels.',
    iconName: 'RefreshCw',
    seoKeyword: 'heic to jpg converter online',
    metaTitle: 'Free Image Format Converter — HEIC to JPG, PNG to WebP | BrowserKit',
    metaDescription: 'Convert HEIC to JPG, PNG to WebP, SVG to PNG, and more for free. Instant batch browser conversion with zero server uploads.',
    faqs: [
      {
        question: 'Can I convert iPhone HEIC photos to JPG?',
        answer: 'Yes! Drop your HEIC files into the converter and they will instantly convert into standard high-resolution JPG images compatible with any software.',
      },
    ],
  },
  resizer: {
    id: 'resizer',
    category: 'image',
    badge: 'Precision',
    title: 'Image Resizer, Cropper & Aspect Ratio Tool',
    subtitle: 'Resize pixel dimensions or crop images for social media, passports, and web assets.',
    description: 'Crop and resize images to exact pixel widths/heights or select aspect ratio presets for Instagram posts, YouTube thumbnails, Passport 2x2 photos, Twitter banners, and web Favicons.',
    iconName: 'Crop',
    seoKeyword: 'resize image online free',
    metaTitle: 'Free Image Resizer & Cropper — Passport & Social Media Presets | BrowserKit',
    metaDescription: 'Resize image dimensions in pixels, percentage, or centimeters. Crop photos for Instagram, Passport 2x2, YouTube thumbnails, and Favicons free.',
    faqs: [
      {
        question: 'Can I resize images for US Passport applications?',
        answer: 'Yes! Select the 2x2 inch Passport photo preset to crop headshots to official requirements.',
      },
    ],
  },
  palette: {
    id: 'palette',
    category: 'image',
    badge: 'Design',
    title: 'Color Palette Extractor & Precision Eyedropper',
    subtitle: 'Extract dominant color palettes and sample exact HEX/RGB/CMYK pixel colors.',
    description: 'Upload any graphic or photograph to automatically generate a harmonized 6-color palette. Use the interactive pixel magnifying eyedropper to copy exact HEX, RGB, HSL, and CMYK color codes.',
    iconName: 'Palette',
    seoKeyword: 'color picker and palette extractor free',
    metaTitle: 'Color Picker & Palette Extractor | BrowserKit',
    metaDescription: 'Extract dominant colors from photos and copy HEX/RGB/CMYK codes with 1 click.',
    faqs: [{ question: 'How does it work?', answer: 'Hover over any image to sample exact HEX/RGB codes.' }],
  },
  meme: {
    id: 'meme',
    category: 'image',
    badge: 'Fun',
    title: 'Free Meme Generator & Text Overlay',
    subtitle: 'Create funny memes and custom text overlays in seconds.',
    description: 'Choose classic meme templates or upload custom images to add draggable text layers with stroke outlines and watermarks.',
    iconName: 'Smile',
    seoKeyword: 'free meme generator online',
    metaTitle: 'Free Meme Generator Online | BrowserKit',
    metaDescription: 'Create custom memes with draggable text boxes and stroke outlines for free.',
    faqs: [{ question: 'Are memes watermarked?', answer: 'No, all exports are 100% clean and watermark-free.' }],
  },
  'video-trimmer': {
    id: 'video-trimmer',
    category: 'video',
    badge: 'New',
    title: 'Video Trimmer, Cutter & Audio Muter',
    subtitle: 'Trim video length, set custom start/end points, or mute audio.',
    description: 'Trim MP4, WebM, MOV, and AVI videos directly in your browser with zero watermark.',
    iconName: 'Video',
    seoKeyword: 'trim video online free no watermark',
    metaTitle: 'Free Video Trimmer & Audio Muter Online | BrowserKit',
    metaDescription: 'Trim video clips online without watermark 100% locally in your browser.',
    faqs: [{ question: 'Are files uploaded?', answer: 'No, video processing runs completely client-side.' }],
  },
  'video-to-gif': {
    id: 'video-to-gif',
    category: 'video',
    badge: 'Utility',
    title: 'Video Frame Extractor & Snapshot Tool',
    subtitle: 'Extract high-resolution image frames and snapshots from any video file.',
    description: 'Capture individual photo frames or continuous image sequences from MP4, WebM, or MOV videos.',
    iconName: 'Film',
    seoKeyword: 'extract frames from video online free',
    metaTitle: 'Free Video Frame Extractor & Snapshot Generator | BrowserKit',
    metaDescription: 'Extract high quality PNG/JPG image frames from videos online for free.',
    faqs: [{ question: 'How many frames?', answer: 'Extract up to 50 frame snapshots per video.' }],
  },

  // === ALL 25+ PDF TOOLS SUITE ===
  'pdf-merger': {
    id: 'pdf-merger',
    category: 'pdf',
    badge: 'Popular',
    title: 'Merge PDF Documents',
    subtitle: 'Combine multiple PDF files into one clean document in the order you want.',
    description: 'Combine separate PDF documents into a single organized PDF file. Drag and drop to reorder files or individual pages.',
    iconName: 'FileText',
    seoKeyword: 'merge pdf files online free',
    metaTitle: 'Free PDF Merger Online — Combine Multiple PDFs Easily | BrowserKit Studio',
    metaDescription: '100% free PDF merger tool. Combine multiple PDF files into a single document with zero file limits.',
    faqs: [{ question: 'Is my PDF secure?', answer: 'Yes! Processing is performed locally inside your browser.' }],
  },
  'pdf-splitter': {
    id: 'pdf-splitter',
    category: 'pdf',
    badge: 'PDF Suite',
    title: 'Split PDF Pages',
    subtitle: 'Separate one page or a whole set into independent PDF files.',
    description: 'Extract specific pages or split multi-page PDF documents into custom standalone PDF files.',
    iconName: 'Scissors',
    seoKeyword: 'split pdf pages free online',
    metaTitle: 'Free PDF Splitter & Page Extractor Online | BrowserKit Studio',
    metaDescription: 'Split PDF files and extract specific page ranges online for free.',
    faqs: [{ question: 'How to extract?', answer: 'Enter page ranges like 1, 3, 5-8.' }],
  },
  'pdf-compressor': {
    id: 'pdf-compressor',
    category: 'pdf',
    badge: 'Popular',
    title: 'Compress PDF',
    subtitle: 'Reduce file size while optimizing for maximal PDF quality.',
    description: 'Compress PDF documents directly inside your browser memory to meet upload size caps.',
    iconName: 'Minimize2',
    seoKeyword: 'compress pdf online free under 200kb',
    metaTitle: 'Free PDF Compressor Online — Reduce PDF File Size | BrowserKit Studio',
    metaDescription: 'Compress PDF files online for free. Reduce document file size locally with zero server uploads.',
    faqs: [{ question: 'Does quality decrease?', answer: 'Our intelligent stream compressor preserves crisp text rendering.' }],
  },
  'pdf-to-word': {
    id: 'pdf-to-word',
    category: 'pdf',
    badge: 'Convert',
    title: 'PDF to Word',
    subtitle: 'Easily convert your PDF files into editable DOC and DOCX documents.',
    description: 'Extract document layout and text from PDF files into editable Microsoft Word documents.',
    iconName: 'FileText',
    seoKeyword: 'convert pdf to word online free',
    metaTitle: 'Free PDF to Word Converter Online — PDF to DOCX | BrowserKit Studio',
    metaDescription: 'Convert PDF files to editable DOCX Word documents online for free.',
    faqs: [{ question: 'Is formatting preserved?', answer: 'Yes, paragraph formatting and text structure are preserved.' }],
  },
  'pdf-to-ppt': {
    id: 'pdf-to-ppt',
    category: 'pdf',
    badge: 'Convert',
    title: 'PDF to PowerPoint',
    subtitle: 'Turn your PDF files into easy to edit PPT and PPTX slideshows.',
    description: 'Transform PDF slides into editable Microsoft PowerPoint presentations.',
    iconName: 'FileText',
    seoKeyword: 'convert pdf to powerpoint online',
    metaTitle: 'Free PDF to PowerPoint Converter — PDF to PPTX | BrowserKit Studio',
    metaDescription: 'Turn PDF documents into editable PPTX slide decks online for free.',
    faqs: [{ question: 'Are slides editable?', answer: 'Yes, slides are converted into editable presentation elements.' }],
  },
  'pdf-to-excel': {
    id: 'pdf-to-excel',
    category: 'pdf',
    badge: 'Convert',
    title: 'PDF to Excel',
    subtitle: 'Pull data straight from PDFs into Excel spreadsheets in seconds.',
    description: 'Extract tables and structured numerical data from PDFs into XLSX spreadsheets.',
    iconName: 'FileText',
    seoKeyword: 'convert pdf to excel online free',
    metaTitle: 'Free PDF to Excel Converter — PDF to XLSX | BrowserKit Studio',
    metaDescription: 'Extract tables straight from PDF files into Excel spreadsheets in seconds.',
    faqs: [{ question: 'Does table structure transfer?', answer: 'Yes, table rows and columns are aligned into Excel cells.' }],
  },
  'word-to-pdf': {
    id: 'word-to-pdf',
    category: 'pdf',
    badge: 'Convert',
    title: 'Word to PDF',
    subtitle: 'Make DOC and DOCX files easy to read by converting them to PDF.',
    description: 'Convert Microsoft Word documents into read-only PDF files with accurate formatting.',
    iconName: 'FilePlus',
    seoKeyword: 'convert word to pdf online free',
    metaTitle: 'Free Word to PDF Converter — DOCX to PDF | BrowserKit Studio',
    metaDescription: 'Convert Word DOC and DOCX files to PDF online for free.',
    faqs: [{ question: 'Is DOCX supported?', answer: 'Yes, both legacy DOC and modern DOCX formats are supported.' }],
  },
  'ppt-to-pdf': {
    id: 'ppt-to-pdf',
    category: 'pdf',
    badge: 'Convert',
    title: 'PowerPoint to PDF',
    subtitle: 'Make PPT and PPTX slideshows easy to view by converting to PDF.',
    description: 'Convert presentation slide decks into portable PDF documents.',
    iconName: 'FilePlus',
    seoKeyword: 'convert powerpoint to pdf free',
    metaTitle: 'Free PowerPoint to PDF Converter — PPT to PDF | BrowserKit Studio',
    metaDescription: 'Convert PPT and PPTX presentation slides to PDF online for free.',
    faqs: [{ question: 'Can I view on mobile?', answer: 'PDFs generated can be viewed on any mobile device or browser.' }],
  },
  'excel-to-pdf': {
    id: 'excel-to-pdf',
    category: 'pdf',
    badge: 'Convert',
    title: 'Excel to PDF',
    subtitle: 'Make EXCEL spreadsheets easy to read by converting to PDF.',
    description: 'Convert XLS and XLSX spreadsheets into clean formatted PDF sheets.',
    iconName: 'FilePlus',
    seoKeyword: 'convert excel to pdf online free',
    metaTitle: 'Free Excel to PDF Converter — XLSX to PDF | BrowserKit Studio',
    metaDescription: 'Convert Excel spreadsheets to PDF documents online for free.',
    faqs: [{ question: 'Are print bounds respected?', answer: 'Yes, table margins and print bounds are formatted nicely.' }],
  },
  'pdf-editor': {
    id: 'pdf-editor',
    category: 'pdf',
    badge: 'Popular',
    title: 'Edit PDF',
    subtitle: 'Add text, images, shapes or freehand annotations to a PDF document.',
    description: 'Edit PDF size, font, and color of added content directly inside your browser.',
    iconName: 'Edit3',
    seoKeyword: 'edit pdf online free no signup',
    metaTitle: 'Free PDF Editor Online — Add Text & Annotations | BrowserKit Studio',
    metaDescription: 'Edit PDF documents online for free. Add text, drawings, and shapes without software.',
    faqs: [{ question: 'Is software installation required?', answer: 'No, runs 100% inside your web browser.' }],
  },
  'pdf-to-jpg': {
    id: 'pdf-to-jpg',
    category: 'pdf',
    badge: 'Popular',
    title: 'PDF to JPG',
    subtitle: 'Convert each PDF page into a JPG or extract images contained in a PDF.',
    description: 'Render PDF pages into high-resolution JPG photos or extract embedded images.',
    iconName: 'Image',
    seoKeyword: 'convert pdf to jpg images online',
    metaTitle: 'Free PDF to JPG Converter Online | BrowserKit Studio',
    metaDescription: 'Convert PDF pages into high quality JPG images online for free.',
    faqs: [{ question: 'What is the image resolution?', answer: 'Export high-DPI 300 DPI image renders.' }],
  },
  'images-to-pdf': {
    id: 'images-to-pdf',
    category: 'pdf',
    badge: 'Popular',
    title: 'JPG to PDF',
    subtitle: 'Convert JPG images to PDF in seconds. Easily adjust orientation & margins.',
    description: 'Convert JPG, PNG, and WebP photos into single or multi-page PDF documents.',
    iconName: 'FilePlus',
    seoKeyword: 'convert jpg to pdf online free',
    metaTitle: 'Free JPG to PDF Converter — Images to PDF | BrowserKit Studio',
    metaDescription: 'Convert JPG images to PDF in seconds with custom orientation and page margins.',
    faqs: [{ question: 'Can I combine multiple photos?', answer: 'Yes, arrange photos into a multi-page PDF document.' }],
  },
  'pdf-signer': {
    id: 'pdf-signer',
    category: 'pdf',
    badge: 'Sign',
    title: 'Sign PDF',
    subtitle: 'Sign yourself or request electronic signatures from others.',
    description: 'Draw e-signatures, upload signature stamps, or type legal signature text onto PDF pages.',
    iconName: 'PenTool',
    seoKeyword: 'sign pdf online free e-signature',
    metaTitle: 'Free PDF Signer Online — Add Electronic Signature | BrowserKit Studio',
    metaDescription: 'Sign PDF documents online for free. Draw e-signatures or add signature text 100% locally.',
    faqs: [{ question: 'Is the e-signature legally binding?', answer: 'Yes, electronic signature stamps are applied to document pages.' }],
  },
  'pdf-watermark': {
    id: 'pdf-watermark',
    category: 'pdf',
    badge: 'PDF Suite',
    title: 'Watermark PDF',
    subtitle: 'Stamp an image or text over your PDF in seconds.',
    description: 'Choose typography, transparency, angle, and position to watermark PDF pages.',
    iconName: 'Stamp',
    seoKeyword: 'add watermark to pdf online free',
    metaTitle: 'Free PDF Watermark Tool — Stamp Text & Logos | BrowserKit Studio',
    metaDescription: 'Add text or image watermarks over PDF documents online for free.',
    faqs: [{ question: 'Can I control opacity?', answer: 'Yes, adjust watermark opacity and rotation angle.' }],
  },
  'pdf-rotator': {
    id: 'pdf-rotator',
    category: 'pdf',
    badge: 'PDF Suite',
    title: 'Rotate PDF',
    subtitle: 'Rotate your PDFs the way you need them. Rotate multiple PDFs at once.',
    description: 'Change PDF page orientation to portrait or landscape with 90°, 180°, or 270° rotation.',
    iconName: 'RotateCw',
    seoKeyword: 'rotate pdf pages online free',
    metaTitle: 'Free PDF Rotator Online — Rotate PDF Pages | BrowserKit Studio',
    metaDescription: 'Rotate PDF pages online for free. Rotate individual or all pages permanently.',
    faqs: [{ question: 'Does rotation save permanently?', answer: 'Yes, page rotation angles are saved directly to the exported PDF.' }],
  },
  'html-to-pdf': {
    id: 'html-to-pdf',
    category: 'pdf',
    badge: 'Convert',
    title: 'HTML to PDF',
    subtitle: 'Convert webpages in HTML to PDF with a single click.',
    description: 'Copy and paste webpage HTML markup or URLs to convert them into readable PDF documents.',
    iconName: 'FileCode',
    seoKeyword: 'convert html to pdf online free',
    metaTitle: 'Free HTML to PDF Converter Online | BrowserKit Studio',
    metaDescription: 'Convert web pages and HTML markup to PDF documents online for free.',
    faqs: [{ question: 'Are CSS styles rendered?', answer: 'Yes, modern layout styles and web fonts are rendered cleanly.' }],
  },
  'pdf-password-remover': {
    id: 'pdf-password-remover',
    category: 'pdf',
    badge: 'Security',
    title: 'Unlock PDF',
    subtitle: 'Remove PDF password security, giving freedom to use your PDFs as you want.',
    description: 'Unlock password-protected PDFs and strip printing, editing, and copying restrictions 100% locally.',
    iconName: 'Unlock',
    seoKeyword: 'remove pdf password online free',
    metaTitle: 'Free PDF Password Remover & Unlocker Online | BrowserKit Studio',
    metaDescription: 'Remove passwords and owner restrictions from PDF files online for free.',
    faqs: [{ question: 'Is my password safe?', answer: 'Yes, decryption happens 100% in your local browser RAM.' }],
  },
  'pdf-protector': {
    id: 'pdf-protector',
    category: 'pdf',
    badge: 'Security',
    title: 'Protect PDF',
    subtitle: 'Protect PDF files with a password. Encrypt PDF documents.',
    description: 'Add password encryption to prevent unauthorized opening, editing, or copying of PDF files.',
    iconName: 'Lock',
    seoKeyword: 'password protect pdf file online free',
    metaTitle: 'Free Protect PDF Online — Add Password Encryption | BrowserKit Studio',
    metaDescription: 'Password protect PDF documents online for free. AES encryption with zero server uploads.',
    faqs: [{ question: 'What encryption level is used?', answer: 'Standard AES 128/256-bit password protection.' }],
  },
  'pdf-organizer': {
    id: 'pdf-organizer',
    category: 'pdf',
    badge: 'PDF Suite',
    title: 'Organize PDF',
    subtitle: 'Sort pages of your PDF file however you like. Delete or add PDF pages.',
    description: 'Reorder PDF thumbnails, delete unwanted pages, or insert new pages into existing PDF documents.',
    iconName: 'Layers',
    seoKeyword: 'organize pdf pages reorder delete',
    metaTitle: 'Free Organize PDF Online — Reorder & Delete Pages | BrowserKit Studio',
    metaDescription: 'Sort, reorder, delete, or add PDF pages online for free.',
    faqs: [{ question: 'Can I delete specific pages?', answer: 'Yes, select any thumbnail to delete or move.' }],
  },
  'pdf-to-pdfa': {
    id: 'pdf-to-pdfa',
    category: 'pdf',
    badge: 'Archive',
    title: 'PDF to PDF/A',
    subtitle: 'Transform your PDF to PDF/A ISO-standardized version for long-term archiving.',
    description: 'Preserve document formatting and embed fonts for long-term legal digital archiving compliance.',
    iconName: 'FileCheck',
    seoKeyword: 'convert pdf to pdfa online free',
    metaTitle: 'Free PDF to PDF/A Converter — Archival Standard | BrowserKit Studio',
    metaDescription: 'Convert PDF documents to ISO-standardized PDF/A format for long-term digital archiving.',
    faqs: [{ question: 'What is PDF/A?', answer: 'ISO-standardized format ensuring documents open identically in the future.' }],
  },
  'pdf-repair': {
    id: 'pdf-repair',
    category: 'pdf',
    badge: 'Utility',
    title: 'Repair PDF',
    subtitle: 'Repair a damaged PDF and recover data from corrupt PDF files.',
    description: 'Fix corrupt page trees and rebuild invalid PDF cross-reference tables automatically.',
    iconName: 'Wand2',
    seoKeyword: 'repair damaged corrupt pdf file online',
    metaTitle: 'Free PDF Repair Tool — Fix Corrupted PDFs | BrowserKit Studio',
    metaDescription: 'Repair damaged or corrupt PDF documents online for free.',
    faqs: [{ question: 'Can it recover unreadable pages?', answer: 'Yes, reconstructs damaged stream objects.' }],
  },
  'pdf-page-numbers': {
    id: 'pdf-page-numbers',
    category: 'pdf',
    badge: 'PDF Suite',
    title: 'Page Numbers',
    subtitle: 'Add page numbers into PDFs with ease. Choose positions & typography.',
    description: 'Stamp customizable page numbers (Page 1 of N) onto header or footer sections of PDF pages.',
    iconName: 'Hash',
    seoKeyword: 'add page numbers to pdf online free',
    metaTitle: 'Free PDF Page Numbering Tool — Add Page Numbers | BrowserKit Studio',
    metaDescription: 'Add customizable page numbers to PDF documents online for free.',
    faqs: [{ question: 'Can I customize position?', answer: 'Yes, place numbers at top-right, bottom-center, or bottom-right.' }],
  },
  'pdf-ocr': {
    id: 'pdf-ocr',
    category: 'pdf',
    badge: 'New',
    title: 'OCR PDF',
    subtitle: 'Convert scanned PDF into searchable and selectable documents.',
    description: 'Extract text overlays from scanned image pages to enable copying and searching in PDF readers.',
    iconName: 'Search',
    seoKeyword: 'ocr pdf online free make text searchable',
    metaTitle: 'Free OCR PDF Online — Searchable PDF Text Generator | BrowserKit Studio',
    metaDescription: 'Convert scanned PDFs into searchable text documents online for free.',
    faqs: [{ question: 'Is OCR accurate?', answer: 'High accuracy optical character recognition engine.' }],
  },
  'pdf-compare': {
    id: 'pdf-compare',
    category: 'pdf',
    badge: 'New',
    title: 'Compare PDF',
    subtitle: 'Show a side-by-side document comparison and easily spot changes.',
    description: 'Compare two versions of a PDF document to highlight text, layout, and image changes.',
    iconName: 'Eye',
    seoKeyword: 'compare two pdf documents online side by side',
    metaTitle: 'Free PDF Comparison Tool — Compare PDF Files | BrowserKit Studio',
    metaDescription: 'Compare two PDF document versions side-by-side online for free.',
    faqs: [{ question: 'How are differences shown?', answer: 'Differences are highlighted side-by-side in real-time.' }],
  },
  'pdf-redact': {
    id: 'pdf-redact',
    category: 'pdf',
    badge: 'Security',
    title: 'Redact PDF',
    subtitle: 'Redact text and graphics to permanently remove sensitive information.',
    description: 'Permanently blackout credit card numbers, SSNs, and personal details from PDF documents.',
    iconName: 'ShieldAlert',
    seoKeyword: 'redact pdf text permanently blackout',
    metaTitle: 'Free PDF Redaction Tool — Blackout Sensitive PDF Text | BrowserKit Studio',
    metaDescription: 'Redact and permanently blackout sensitive text from PDF documents online for free.',
    faqs: [{ question: 'Is redaction permanent?', answer: 'Yes, underlying vector text and streams are completely removed.' }],
  },
  'pdf-cropper': {
    id: 'pdf-cropper',
    category: 'pdf',
    badge: 'PDF Suite',
    title: 'Crop PDF',
    subtitle: 'Crop margins of PDF documents or select specific areas.',
    description: 'Trim white margins or crop specific rectangular bounds on PDF document pages.',
    iconName: 'Crop',
    seoKeyword: 'crop pdf margins online free',
    metaTitle: 'Free PDF Cropper Online — Crop PDF Margins | BrowserKit Studio',
    metaDescription: 'Crop PDF margins and adjust document bounding boxes online for free.',
    faqs: [{ question: 'Can I crop all pages at once?', answer: 'Yes, apply margin crop settings to one page or all pages.' }],
  },
  'pdf-forms': {
    id: 'pdf-forms',
    category: 'pdf',
    badge: 'New',
    title: 'PDF Forms',
    subtitle: 'Detect form fields automatically, create interactive fillable PDFs.',
    description: 'Fill out interactive PDF forms, check boxes, select radio buttons, and add text fields.',
    iconName: 'CheckCircle',
    seoKeyword: 'fill pdf form online free fillable pdf',
    metaTitle: 'Free Interactive PDF Form Filler & Builder | BrowserKit Studio',
    metaDescription: 'Fill out interactive PDF forms online for free. Add text fields and checkboxes.',
    faqs: [{ question: 'Can I save filled forms?', answer: 'Yes, save filled interactive PDF forms directly to disk.' }],
  },
  'pdf-ai-summarizer': {
    id: 'pdf-ai-summarizer',
    category: 'pdf',
    badge: 'AI Powered',
    title: 'AI PDF Summarizer',
    subtitle: 'Quickly generate concise summaries from articles, paragraphs & essays.',
    description: 'Extract executive summaries, key bullet points, and main highlights from multi-page PDFs using client-side AI.',
    iconName: 'Sparkles',
    seoKeyword: 'ai pdf summarizer online free',
    metaTitle: 'Free AI PDF Summarizer — Extract Key Points | BrowserKit Studio',
    metaDescription: 'Generate concise executive summaries from PDF articles and essays online for free.',
    faqs: [{ question: 'Is my document sent to external AI servers?', answer: 'No, processing occurs 100% locally.' }],
  },
  'pdf-translate': {
    id: 'pdf-translate',
    category: 'pdf',
    badge: 'AI Powered',
    title: 'Translate PDF',
    subtitle: 'Easily translate PDF files powered by AI while keeping layout intact.',
    description: 'Translate PDF documents into Spanish, French, German, Hindi, and more while preserving visual layout.',
    iconName: 'Languages',
    seoKeyword: 'translate pdf document online free',
    metaTitle: 'Free AI PDF Translator — Translate PDF Documents | BrowserKit Studio',
    metaDescription: 'Translate PDF documents online for free while keeping fonts and layout intact.',
    faqs: [{ question: 'Which languages are supported?', answer: 'Supports over 50+ international languages.' }],
  },
  'pdf-to-markdown': {
    id: 'pdf-to-markdown',
    category: 'pdf',
    badge: 'Developer',
    title: 'PDF to Markdown',
    subtitle: 'Easily turn PDFs into structured Markdown documents.',
    description: 'Extract headings, paragraphs, code blocks, and tables into clean Markdown (.md) markup.',
    iconName: 'FileCode',
    seoKeyword: 'convert pdf to markdown md online',
    metaTitle: 'Free PDF to Markdown Converter — PDF to MD | BrowserKit Studio',
    metaDescription: 'Turn PDF files into clean Markdown documents online for free.',
    faqs: [{ question: 'Can I export .md files?', answer: 'Yes, download formatted .md markdown documents with 1 click.' }],
  },

  // Archive & Security
  'zip-archiver': {
    id: 'zip-archiver',
    category: 'zip',
    badge: 'ZIP Suite',
    title: 'ZIP Creator & File Archiver',
    subtitle: 'Compress images, documents, and videos into a downloadable .zip package.',
    description: 'Combine files into a compressed .zip archive directly in your browser.',
    iconName: 'Archive',
    seoKeyword: 'create zip file online free',
    metaTitle: 'Free ZIP Creator Online | BrowserKit Studio',
    metaDescription: 'Create .zip compressed archives online for free with zero server uploads.',
    faqs: [{ question: 'Size limit?', answer: 'Create archives up to hundreds of megabytes in browser RAM.' }],
  },
  'zip-extractor': {
    id: 'zip-extractor',
    category: 'zip',
    badge: 'ZIP Suite',
    title: 'ZIP Extractor & Archive Viewer',
    subtitle: 'Inspect and extract files from .zip archives without uploading.',
    description: 'Drop any .zip archive to view contents, file sizes, and extract individual files.',
    iconName: 'FolderArchive',
    seoKeyword: 'extract zip file online free',
    metaTitle: 'Free ZIP Extractor Online | BrowserKit Studio',
    metaDescription: 'Unzip and extract files from .zip archives online for free.',
    faqs: [{ question: 'Inspect zip?', answer: 'Yes, preview file list before extracting.' }],
  },
  'zip-password-remover': {
    id: 'zip-password-remover',
    category: 'zip',
    badge: 'Security',
    title: 'ZIP Password Remover',
    subtitle: 'Unlock password-protected ZIP archives and extract all contents.',
    description: 'Unlock encrypted ZIP archives and extract all contained files 100% locally.',
    iconName: 'Unlock',
    seoKeyword: 'unlock password protected zip file online',
    metaTitle: 'Free ZIP Password Remover & Unlocker Online | BrowserKit Studio',
    metaDescription: 'Unlock password-protected ZIP archives online for free.',
    faqs: [{ question: 'How it works?', answer: 'Decrypts zip archives locally inside browser RAM.' }],
  },
  'audio-tools': {
    id: 'audio-tools',
    category: 'audio',
    badge: 'Audio',
    title: 'Audio Converter & Sound Extractor',
    subtitle: 'Convert audio formats or extract high quality audio tracks from video files.',
    description: 'Convert audio recordings between MP3, WAV, OGG, and extract audio from MP4 videos.',
    iconName: 'Music',
    seoKeyword: 'extract audio from mp4 free',
    metaTitle: 'Free Audio Converter & Video Audio Extractor | BrowserKit Studio',
    metaDescription: 'Extract audio from video and convert audio formats online for free.',
    faqs: [{ question: 'Which formats?', answer: 'MP3, WAV, OGG, WebM, AAC, and M4A.' }],
  },
  'svg-optimizer': {
    id: 'svg-optimizer',
    category: 'image',
    badge: 'Developer',
    title: 'SVG Cleaner & Minifier',
    subtitle: 'Minify raw SVG markup, strip editor metadata, or convert SVG to PNG.',
    description: 'Clean up vector graphics created in Figma, Illustrator, or Inkscape.',
    iconName: 'Code',
    seoKeyword: 'svg optimizer minifier online',
    metaTitle: 'Free SVG Cleaner, Minifier & PNG Rasterizer | BrowserKit Studio',
    metaDescription: 'Optimize and minify SVG markup online for free.',
    faqs: [{ question: 'Breaks styling?', answer: 'No, strips only redundant comments and unused tags.' }],
  },
  'file-encryptor': {
    id: 'file-encryptor',
    category: 'zip',
    badge: 'Security',
    title: 'Client-Side File Encryptor (AES-256 Vault)',
    subtitle: 'Encrypt photos, videos, PDFs, and documents with military-grade password vaulting.',
    description: 'Protect sensitive files using AES-256-GCM encryption with PBKDF2 password derivation.',
    iconName: 'Lock',
    seoKeyword: 'password encrypt file online free',
    metaTitle: 'Free File Encryptor — AES-256 Password Protect | BrowserKit Studio',
    metaDescription: 'Encrypt photos, PDFs, documents, and ZIP files with password protection online for free.',
    faqs: [{ question: 'Unbreakable?', answer: 'Yes, AES-256 is mathematically unbreakable without password.' }],
  },
};

export function generateSitemapXML(routes?: any): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>https://browserkit.co.in/</loc></url>
</urlset>`;
}

export function generateRobotsTxt(domain?: any): string {
  return `User-agent: *\nAllow: /\n\nSitemap: https://browserkit.co.in/sitemap.xml`;
}
