import { ToolMeta, ToolType } from '../types';

export const TOOL_METADATA: Record<ToolType, ToolMeta> = {
  compressor: {
    id: 'compressor',
    category: 'image',
    badge: 'Most Popular',
    title: 'Client-Side Image Compressor',
    subtitle: 'Shrink PNG, JPG, and WebP images by up to 90% without quality loss.',
    description: 'Compress single or batch images locally in your browser. Set target file size caps (under 50KB, 100KB, 200KB), fine-tune compression quality, compare side-by-side previews, and download instantly with zero server uploads.',
    iconName: 'Minimize2',
    seoKeyword: 'compress image online free',
    metaTitle: 'Free Image Compressor Online — Compress PNG & JPG Under 100KB | BrowserKit',
    metaDescription: 'Compress images online for free. Reduce PNG, JPG, WebP file sizes by up to 90% in your browser. Target exact KB sizes with zero server uploads.',
    faqs: [
      {
        question: 'Is my data private when compressing images?',
        answer: 'Yes, 100%. Processing runs entirely inside your browser memory using HTML5 Canvas APIs. Your images are never uploaded to any remote server.',
      },
    ],
  },
  converter: {
    id: 'converter',
    category: 'image',
    badge: 'High Speed',
    title: 'Universal Image Format Converter',
    subtitle: 'Convert between HEIC, PNG, JPG, WebP, GIF, BMP, and SVG formats.',
    description: 'Batch convert iPhone HEIC photos, modern WebP graphics, vector SVGs, and PNG/JPG photos. Preserves EXIF metadata, original dimensions, and transparency channels.',
    iconName: 'RefreshCw',
    seoKeyword: 'heic to jpg converter online',
    metaTitle: 'Free Image Format Converter — HEIC to JPG, PNG to WebP | BrowserKit',
    metaDescription: 'Convert HEIC to JPG, PNG to WebP, SVG to PNG, and more for free. Instant batch browser conversion with zero server uploads.',
    faqs: [
      {
        question: 'Can I convert iPhone HEIC photos to JPG?',
        answer: 'Yes! Drop your HEIC files into the converter and they will instantly convert into standard high-resolution JPG images compatible with any software.',
      },
    ],
  },
  resizer: {
    id: 'resizer',
    category: 'image',
    badge: 'Precision',
    title: 'Image Resizer, Cropper & Aspect Ratio Tool',
    subtitle: 'Resize pixel dimensions or crop images for social media, passports, and web assets.',
    description: 'Crop and resize images to exact pixel widths/heights or select aspect ratio presets for Instagram posts, YouTube thumbnails, Passport 2x2 photos, Twitter banners, and web Favicons.',
    iconName: 'Crop',
    seoKeyword: 'resize image online free',
    metaTitle: 'Free Image Resizer & Cropper — Passport & Social Media Presets | BrowserKit',
    metaDescription: 'Resize image dimensions in pixels, percentage, or centimeters. Crop photos for Instagram, Passport 2x2, YouTube thumbnails, and Favicons free.',
    faqs: [
      {
        question: 'Can I resize images for US Passport applications?',
        answer: 'Yes! Select the 2x2 inch Passport photo preset to crop headshots to official requirements.',
      },
    ],
  },
  palette: {
    id: 'palette',
    category: 'image',
    badge: 'Design',
    title: 'Color Palette Extractor & Precision Eyedropper',
    subtitle: 'Extract dominant color palettes and sample exact HEX/RGB/CMYK pixel colors.',
    description: 'Upload any graphic or photograph to automatically generate a harmonized 6-color palette. Use the interactive pixel magnifying eyedropper to copy exact HEX, RGB, HSL, and CMYK color codes.',
    iconName: 'Palette',
    seoKeyword: 'color picker and palette extractor free',
    metaTitle: 'Color Picker & Palette Extractor | BrowserKit',
    metaDescription: 'Extract dominant colors from photos and copy HEX/RGB/CMYK codes with 1 click.',
    faqs: [{ question: 'How does it work?', answer: 'Hover over any image to sample exact HEX/RGB codes.' }],
  },
  meme: {
    id: 'meme',
    category: 'image',
    badge: 'Fun',
    title: 'Free Meme Generator & Text Overlay',
    subtitle: 'Create funny memes and custom text overlays in seconds.',
    description: 'Choose classic meme templates or upload custom images to add draggable text layers with stroke outlines and watermarks.',
    iconName: 'Smile',
    seoKeyword: 'free meme generator online',
    metaTitle: 'Free Meme Generator Online | BrowserKit Studio',
    metaDescription: 'Create custom memes with draggable text boxes and stroke outlines for free.',
    faqs: [{ question: 'Are memes watermarked?', answer: 'No, all exports are 100% clean and watermark-free.' }],
  },
  'passport-photo-maker': {
    id: 'passport-photo-maker',
    category: 'image',
    badge: 'Popular',
    title: 'Passport Photo Maker & Background Changer',
    subtitle: 'Create official 3.5x4.5cm, 2x2 inch, or 35x45mm passport photos with white/blue/red backgrounds.',
    description: 'Format photos for US Passport, Indian SSC, Schengen Visa, and PAN Card with custom background colors.',
    iconName: 'UserCheck',
    seoKeyword: 'passport size photo maker online free',
    metaTitle: 'Free Passport Photo Maker — White/Blue Background Changer | BrowserKit Studio',
    metaDescription: 'Make passport photos online for free. Change background color to white, blue, or red for SSC, UPSC, US Visa.',
    faqs: [{ question: 'What sizes are supported?', answer: 'Supports 3.5cm x 4.5cm, 2x2 inch, 35mm x 45mm, and 600x600 px.' }],
  },
  'add-name-and-dob': {
    id: 'add-name-and-dob',
    category: 'image',
    badge: 'Govt Exams',
    title: 'Add Name & Date of Birth (DOB) on Photo',
    subtitle: 'Stamp candidate name and date of photo / DOB at the bottom of exam photos.',
    description: 'Add mandatory name and date stamp for SSC, UPSC, Railway, and State PSC application forms.',
    iconName: 'Calendar',
    seoKeyword: 'add name and date on photo online free',
    metaTitle: 'Add Name & Date on Photo for SSC & UPSC Online | BrowserKit Studio',
    metaDescription: 'Add candidate name and date of photo / DOB on photos for SSC, UPSC, and govt exam forms free.',
    faqs: [{ question: 'Is this required for SSC?', answer: 'Yes, SSC & State PSC forms require printed name and date.' }],
  },
  'signature-resizer': {
    id: 'signature-resizer',
    category: 'image',
    badge: 'Govt Exams',
    title: 'Resize Signature (6cm x 2cm, 300 DPI)',
    subtitle: 'Resize signature dimensions to exact centimeters or 300 DPI requirements.',
    description: 'Resize signature scans to 6cm x 2cm, 50mm x 20mm, or under 20KB for online forms.',
    iconName: 'PenTool',
    seoKeyword: 'resize signature 6cm x 2cm 300 dpi online',
    metaTitle: 'Free Signature Resizer — 6cm x 2cm @ 300 DPI | BrowserKit Studio',
    metaDescription: 'Resize signature images for SSC, PAN Card, and UPSC exam applications online for free.',
    faqs: [{ question: 'Does it support 300 DPI?', answer: 'Yes, outputs exact 300 DPI signature dimensions.' }],
  },
  'image-dpi-converter': {
    id: 'image-dpi-converter',
    category: 'image',
    badge: 'Precision',
    title: 'Convert Image DPI (200, 300, 600 DPI)',
    subtitle: 'Change DPI density metadata for print and official document uploads.',
    description: 'Convert image resolution to 200 DPI, 300 DPI, or 600 DPI without altering physical pixels.',
    iconName: 'Sliders',
    seoKeyword: 'convert image dpi 300 online free',
    metaTitle: 'Free Image DPI Converter — Convert to 200, 300, 600 DPI | BrowserKit Studio',
    metaDescription: 'Convert image DPI density to 200, 300, or 600 DPI online for free.',
    faqs: [{ question: 'What is DPI?', answer: 'Dots Per Inch metadata determining printing density.' }],
  },
  'circle-crop': {
    id: 'circle-crop',
    category: 'image',
    badge: 'Design',
    title: 'Circle & Round Corner Image Cropper',
    subtitle: 'Crop photos into perfect circular avatars or add rounded corners.',
    description: 'Crop profile photos into circles or adjust corner radius for social media avatars.',
    iconName: 'Crop',
    seoKeyword: 'crop circle image online free',
    metaTitle: 'Free Circle Image Cropper & Round Corners Tool | BrowserKit Studio',
    metaDescription: 'Crop images into clean circular avatars or add rounded corners online for free.',
    faqs: [{ question: 'Is output transparent?', answer: 'Yes, circular crops export with clean PNG transparency.' }],
  },
  'merge-photo-signature': {
    id: 'merge-photo-signature',
    category: 'image',
    badge: 'Govt Exams',
    title: 'Merge Photo & Signature into One File',
    subtitle: 'Join photo and signature vertically into a single uploaded document.',
    description: 'Combine passport photograph and signature scan vertically for exam applications.',
    iconName: 'Layers',
    seoKeyword: 'merge photo and signature online free',
    metaTitle: 'Merge Photo & Signature Online — Combine into 1 Image | BrowserKit Studio',
    metaDescription: 'Merge passport photo and signature into a single file for government applications free.',
    faqs: [{ question: 'How is it formatted?', answer: 'Photo on top, signature on bottom with a clean dividing line.' }],
  },
  'join-images': {
    id: 'join-images',
    category: 'image',
    badge: 'Utility',
    title: 'Join & Stitch Multiple Images',
    subtitle: 'Combine multiple photos horizontally or vertically into a single image.',
    description: 'Stitch photo side-by-side or stack pictures vertically with customizable spacing.',
    iconName: 'FilePlus',
    seoKeyword: 'join multiple images online side by side',
    metaTitle: 'Free Image Joiner & Photo Stitcher Online | BrowserKit Studio',
    metaDescription: 'Join and stitch multiple photos horizontally or vertically online for free.',
    faqs: [{ question: 'How many images?', answer: 'Join up to 10 images into a single photo layout.' }],
  },
  'image-watermark': {
    id: 'image-watermark',
    category: 'image',
    badge: 'Security',
    title: 'Watermark Images (Text & Logo)',
    subtitle: 'Add text or logo watermarks over photos with custom opacity.',
    description: 'Protect online photography and document uploads with custom watermark text overlays.',
    iconName: 'Shield',
    seoKeyword: 'add watermark to photo online free',
    metaTitle: 'Free Photo Watermark Tool — Add Text & Logos | BrowserKit Studio',
    metaDescription: 'Add text or logo watermarks over images online for free.',
    faqs: [{ question: 'Can I adjust opacity?', answer: 'Yes, adjust watermark text opacity and rotation angle.' }],
  },
  'image-rotate-flip': {
    id: 'image-rotate-flip',
    category: 'image',
    badge: 'Utility',
    title: 'Rotate & Flip Image',
    subtitle: 'Rotate photos 90°, 180°, 270° or flip horizontally and vertically.',
    description: 'Fix upside-down photos and mirror camera selfies 100% locally.',
    iconName: 'RotateCw',
    seoKeyword: 'rotate flip image online free',
    metaTitle: 'Free Image Rotator & Flipper Online | BrowserKit Studio',
    metaDescription: 'Rotate photos 90/180/270 degrees or flip horizontally online for free.',
    faqs: [{ question: 'Saves permanently?', answer: 'Yes, rotation is applied directly to the image output file.' }],
  },
  'image-effects': {
    id: 'image-effects',
    category: 'image',
    badge: 'Effects',
    title: 'Blur, Pixelate & Photo Effects',
    subtitle: 'Apply grayscale, black & white, blur background, or pixelate faces.',
    description: 'Obfuscate sensitive details or convert photos to black & white graphics.',
    iconName: 'Eye',
    seoKeyword: 'blur pixelate image online free',
    metaTitle: 'Free Photo Effects — Grayscale, Blur & Pixelate | BrowserKit Studio',
    metaDescription: 'Apply blur, pixelate faces, or convert photos to grayscale online for free.',
    faqs: [{ question: 'Is processing private?', answer: 'Yes, effect processing is performed completely in your browser.' }],
  },
  'official-size-resizer': {
    id: 'official-size-resizer',
    category: 'image',
    badge: 'Govt Exams',
    title: 'Resize Image for Official Forms (SSC, UPSC, PAN Card)',
    subtitle: 'Resize photo dimensions for SSC CGL, UPSC IAS, PAN Card, and State PSC.',
    description: 'Presets for SSC (3.5x4.5cm), PAN Card (2.5x3.5cm), and UPSC online portals.',
    iconName: 'UserCheck',
    seoKeyword: 'resize image for ssc upsc pan card free',
    metaTitle: 'Free Official Exam Photo Resizer — SSC, UPSC, PAN Card | BrowserKit Studio',
    metaDescription: 'Resize photos for SSC CGL, UPSC, and PAN Card forms online for free.',
    faqs: [{ question: 'Are dimensions accurate?', answer: 'Yes, dimensions strictly match government requirements.' }],
  },
  'social-media-resizer': {
    id: 'social-media-resizer',
    category: 'image',
    badge: 'Social',
    title: 'Social Media Image Resizer & Banner Maker',
    subtitle: 'Resize for Instagram No-Crop, WhatsApp DP, YouTube Banner, Twitter Header.',
    description: 'Format photos for Instagram posts, YouTube banners, and WhatsApp profile photos.',
    iconName: 'Crop',
    seoKeyword: 'resize image for instagram whatsapp dp youtube banner',
    metaTitle: 'Free Social Media Resizer — Instagram, WhatsApp DP, YouTube | BrowserKit Studio',
    metaDescription: 'Resize images for Instagram grid, WhatsApp DP, and YouTube banners free.',
    faqs: [{ question: 'No crop supported?', answer: 'Yes, auto-pad background for Instagram No-Crop.' }],
  },
  'target-kb-compressor': {
    id: 'target-kb-compressor',
    category: 'image',
    badge: 'Popular',
    title: 'Reduce Image Size in KB (Under 20KB, 50KB, 100KB, 200KB)',
    subtitle: 'Compress images to exact target KB size limits automatically.',
    description: 'Compress JPG, PNG, and WebP images under 20KB, 50KB, 100KB, or 200KB for portal uploads.',
    iconName: 'Minimize2',
    seoKeyword: 'reduce image size in kb under 20kb 50kb 100kb',
    metaTitle: 'Reduce Image Size in KB — Under 20KB, 50KB, 100KB Free | BrowserKit Studio',
    metaDescription: 'Compress images under 20KB, 50KB, 100KB, 200KB online for free with zero server uploads.',
    faqs: [{ question: 'How to reach exact KB?', answer: 'Intelligent binary search adjusts compression factor automatically.' }],
  },
  'video-trimmer': {
    id: 'video-trimmer',
    category: 'video',
    badge: 'Popular',
    title: 'Video Trimmer, Cutter & Precision Cropper',
    subtitle: 'Trim video length, set custom start/end timestamps, or crop rectangular bounds.',
    description: 'Trim MP4, WebM, MOV, and AVI videos directly in your browser with zero watermark.',
    iconName: 'Video',
    seoKeyword: 'trim video online free no watermark',
    metaTitle: 'Free Video Trimmer & Precision Cropper Online | BrowserKit Studio',
    metaDescription: 'Trim video clips online without watermark 100% locally in your browser.',
    faqs: [{ question: 'Are files uploaded?', answer: 'No, video processing runs completely client-side.' }],
  },
  'video-to-gif': {
    id: 'video-to-gif',
    category: 'video',
    badge: 'Utility',
    title: 'Video Frame Extractor & Snapshot Tool',
    subtitle: 'Extract high-resolution image frames and snapshots from any video file.',
    description: 'Capture individual photo frames or continuous image sequences from MP4, WebM, or MOV videos.',
    iconName: 'Film',
    seoKeyword: 'extract frames from video online free',
    metaTitle: 'Free Video Frame Extractor & Snapshot Generator | BrowserKit Studio',
    metaDescription: 'Extract high quality PNG/JPG image frames from videos online for free.',
    faqs: [{ question: 'How many frames?', answer: 'Extract up to 50 frame snapshots per video.' }],
  },
  'social-video-downloader': {
    id: 'social-video-downloader',
    category: 'video',
    badge: 'Social',
    title: 'Social Video Link Downloader (HD 1080p / 4K)',
    subtitle: 'Paste social media video links to save high-definition video files directly.',
    description: 'Save 1080p/4K social media video links locally without third-party popups or watermark.',
    iconName: 'Video',
    seoKeyword: 'social video downloader online hd free',
    metaTitle: 'Free Social Video Downloader Online — HD 1080p & 4K | BrowserKit Studio',
    metaDescription: 'Download HD 1080p/4K videos from social links free online without watermarks or popups.',
    faqs: [{ question: 'Is it free?', answer: 'Yes, 100% free with unlimited downloads.' }],
  },
  'social-audio-extractor': {
    id: 'social-audio-extractor',
    category: 'audio',
    badge: 'Audio',
    title: 'Social Media Audio Extractor',
    subtitle: 'Extract pristine MP3 audio tracks directly from social media video links.',
    description: 'Rip audio tracks from video URLs in 320kbps MP3 format for ringtones and music collection.',
    iconName: 'Music',
    seoKeyword: 'extract audio from video link free',
    metaTitle: 'Free Social Audio Extractor — Rip MP3 Audio from Video Links | BrowserKit Studio',
    metaDescription: 'Extract 320kbps MP3 audio from social video URLs free online with 1 click.',
    faqs: [{ question: 'What bitrate is exported?', answer: 'Supports up to 320kbps MP3 audio quality.' }],
  },
  'social-batch-downloader': {
    id: 'social-batch-downloader',
    category: 'video',
    badge: 'Batch',
    title: 'Batch Link Video & Media Downloader',
    subtitle: 'Paste multiple URLs or playlist links to queue several files at once.',
    description: 'Batch download social media videos and audio files in 1 click.',
    iconName: 'Layers',
    seoKeyword: 'batch video downloader playlist online free',
    metaTitle: 'Free Batch Video & Playlist Downloader | BrowserKit Studio',
    metaDescription: 'Paste multiple video URLs or playlist links to download files in bulk free.',
    faqs: [{ question: 'How many links at once?', answer: 'Queue up to 20 media links simultaneously.' }],
  },
  'thumbnail-grabber': {
    id: 'thumbnail-grabber',
    category: 'video',
    badge: 'Popular',
    title: 'HD Video Thumbnail & Cover Grabber',
    subtitle: 'Extract and download high-resolution cover images or thumbnails from any video link.',
    description: 'Download 4K / 1080p max-res cover images from YouTube, Vimeo, and social video links.',
    iconName: 'Image',
    seoKeyword: 'youtube thumbnail downloader maxresdefault',
    metaTitle: 'Free HD Video Thumbnail Grabber — Download 4K Cover Images | BrowserKit Studio',
    metaDescription: 'Download high-res HD 4K thumbnails and cover artwork from video links online for free.',
    faqs: [{ question: 'What resolution is saved?', answer: 'Fetches maxresdefault 1080p/4K cover artwork.' }],
  },
  'video-to-audio': {
    id: 'video-to-audio',
    category: 'audio',
    badge: 'Converter',
    title: 'Video to Audio Converter (MP3 320kbps / WAV)',
    subtitle: 'Convert video files into pristine 320kbps MP3 or lossless WAV audio files.',
    description: 'Extract audio tracks from MP4, WebM, MOV, and AVI files locally inside your browser.',
    iconName: 'Music',
    seoKeyword: 'convert video to mp3 320kbps online free',
    metaTitle: 'Free Video to MP3 Audio Converter — 320kbps High Quality | BrowserKit Studio',
    metaDescription: 'Convert MP4, WebM, MOV videos to 320kbps MP3 audio tracks online free.',
    faqs: [{ question: 'Is processing private?', answer: 'Yes, audio extraction runs 100% locally in browser memory.' }],
  },
  'video-format-swapper': {
    id: 'video-format-swapper',
    category: 'video',
    badge: 'Converter',
    title: 'Video Format Swapper (MOV to MP4, WebM to MP4)',
    subtitle: 'Change video formats instantly for universal device and TV playback compatibility.',
    description: 'Convert iPhone MOV videos, WebM browser clips, and AVI files to universal MP4 format.',
    iconName: 'RefreshCw',
    seoKeyword: 'mov to mp4 converter webm to mp4 free',
    metaTitle: 'Free Video Format Swapper — MOV to MP4, WebM to MP4 | BrowserKit Studio',
    metaDescription: 'Convert MOV to MP4, WebM to MP4, and AVI to MP4 online free with zero cloud uploads.',
    faqs: [{ question: 'Will quality decrease?', answer: 'Original video resolution and bitrate are maintained.' }],
  },
  'gif-maker': {
    id: 'gif-maker',
    category: 'video',
    badge: 'Media',
    title: 'Video to Animated GIF Maker',
    subtitle: 'Convert short video clips or social links directly into animated GIFs.',
    description: 'Create high-framerate animated GIF clips from MP4, WebM, or MOV videos for Discord and Twitter.',
    iconName: 'Sparkles',
    seoKeyword: 'video to gif converter online free',
    metaTitle: 'Free Video to GIF Converter — Create Animated GIFs Online | BrowserKit Studio',
    metaDescription: 'Convert video clips into animated GIF files free online with custom FPS and dimensions.',
    faqs: [{ question: 'Are watermarks added?', answer: 'No, all exported GIFs are 100% clean and unwatermarked.' }],
  },
  'video-codec-transcoder': {
    id: 'video-codec-transcoder',
    category: 'video',
    badge: 'Codec',
    title: 'Video Codec Transcoder & Stream Compressor',
    subtitle: 'Transcode videos to H.265 / AV1 codecs to compress file size by up to 70%.',
    description: 'Re-encode video bitrates and modern codecs for fast web streaming and low bandwidth.',
    iconName: 'Code',
    seoKeyword: 'video codec transcoder h265 av1 compress free',
    metaTitle: 'Free Video Codec Transcoder — H.265 & AV1 Compression | BrowserKit Studio',
    metaDescription: 'Transcode and compress video bitrates to H.265 and AV1 online free with zero server uploads.',
    faqs: [{ question: 'How much file size is saved?', answer: 'Saves up to 70% video file size with minimal visual loss.' }],
  },
  'audio-cutter': {
    id: 'audio-cutter',
    category: 'audio',
    badge: 'Popular',
    title: 'Audio Cutter & Custom Ringtone Generator',
    subtitle: 'Trim audio files with a visual waveform scrubber to create custom ringtones.',
    description: 'Cut MP3, WAV, AAC, and OGG audio tracks to custom start/end timestamps.',
    iconName: 'Scissors',
    seoKeyword: 'audio cutter mp3 trimmer ringtone maker free',
    metaTitle: 'Free Audio Cutter & Ringtone Maker — Trim MP3 Online | BrowserKit Studio',
    metaDescription: 'Trim audio files and make custom MP3 ringtones online for free with visual waveform editing.',
    faqs: [{ question: 'Supports iPhone ringtones?', answer: 'Yes, exports MP3 and M4R ringtone formats.' }],
  },
  'aspect-ratio-resizer': {
    id: 'aspect-ratio-resizer',
    category: 'video',
    badge: 'Popular',
    title: 'Video Aspect Ratio Resizer (9:16 TikTok, 1:1 IG, 16:9 YT)',
    subtitle: 'Instantly crop or pad videos to fit TikTok/Reels (9:16) or Instagram Feed (1:1).',
    description: 'Convert landscape 16:9 videos to vertical 9:16 TikTok Reels with blurred background padding.',
    iconName: 'Crop',
    seoKeyword: 'resize video aspect ratio 9 16 tiktok reels instagram free',
    metaTitle: 'Free Video Aspect Ratio Resizer — 9:16 Reels & TikTok | BrowserKit Studio',
    metaDescription: 'Resize video aspect ratios to 9:16 vertical for TikTok & Reels, or 1:1 for Instagram online free.',
    faqs: [{ question: 'Does it add blurred background?', answer: 'Yes, fills side bars with blurred video padding automatically.' }],
  },

  // === ALL 25+ PDF TOOLS SUITE ===
  'pdf-merger': {
    id: 'pdf-merger',
    category: 'pdf',
    badge: 'Popular',
    title: 'Merge PDF Documents',
    subtitle: 'Combine multiple PDF files into one clean document in the order you want.',
    description: 'Combine separate PDF documents into a single organized PDF file. Drag and drop to reorder files or individual pages.',
    iconName: 'FileText',
    seoKeyword: 'merge pdf files online free',
    metaTitle: 'Free PDF Merger Online — Combine Multiple PDFs Easily | BrowserKit Studio',
    metaDescription: '100% free PDF merger tool. Combine multiple PDF files into a single document with zero file limits.',
    faqs: [{ question: 'Is my PDF secure?', answer: 'Yes! Processing is performed locally inside your browser.' }],
  },
  'pdf-splitter': {
    id: 'pdf-splitter',
    category: 'pdf',
    badge: 'PDF Suite',
    title: 'Split PDF Pages',
    subtitle: 'Separate one page or a whole set into independent PDF files.',
    description: 'Extract specific pages or split multi-page PDF documents into custom standalone PDF files.',
    iconName: 'Scissors',
    seoKeyword: 'split pdf pages free online',
    metaTitle: 'Free PDF Splitter & Page Extractor Online | BrowserKit Studio',
    metaDescription: 'Split PDF files and extract specific page ranges online for free.',
    faqs: [{ question: 'How to extract?', answer: 'Enter page ranges like 1, 3, 5-8.' }],
  },
  'pdf-compressor': {
    id: 'pdf-compressor',
    category: 'pdf',
    badge: 'Popular',
    title: 'Compress PDF',
    subtitle: 'Reduce file size while optimizing for maximal PDF quality.',
    description: 'Compress PDF documents directly inside your browser memory to meet upload size caps.',
    iconName: 'Minimize2',
    seoKeyword: 'compress pdf online free under 200kb',
    metaTitle: 'Free PDF Compressor Online — Reduce PDF File Size | BrowserKit Studio',
    metaDescription: 'Compress PDF files online for free. Reduce document file size locally with zero server uploads.',
    faqs: [{ question: 'Does quality decrease?', answer: 'Our intelligent stream compressor preserves crisp text rendering.' }],
  },
  'pdf-to-word': {
    id: 'pdf-to-word',
    category: 'pdf',
    badge: 'Convert',
    title: 'PDF to Word',
    subtitle: 'Easily convert your PDF files into editable DOC and DOCX documents.',
    description: 'Extract document layout and text from PDF files into editable Microsoft Word documents.',
    iconName: 'FileText',
    seoKeyword: 'convert pdf to word online free',
    metaTitle: 'Free PDF to Word Converter Online — PDF to DOCX | BrowserKit Studio',
    metaDescription: 'Convert PDF files to editable DOCX Word documents online for free.',
    faqs: [{ question: 'Is formatting preserved?', answer: 'Yes, paragraph formatting and text structure are preserved.' }],
  },
  'pdf-to-ppt': {
    id: 'pdf-to-ppt',
    category: 'pdf',
    badge: 'Convert',
    title: 'PDF to PowerPoint',
    subtitle: 'Turn your PDF files into easy to edit PPT and PPTX slideshows.',
    description: 'Transform PDF slides into editable Microsoft PowerPoint presentations.',
    iconName: 'FileText',
    seoKeyword: 'convert pdf to powerpoint online',
    metaTitle: 'Free PDF to PowerPoint Converter — PDF to PPTX | BrowserKit Studio',
    metaDescription: 'Turn PDF documents into editable PPTX slide decks online for free.',
    faqs: [{ question: 'Are slides editable?', answer: 'Yes, slides are converted into editable presentation elements.' }],
  },
  'pdf-to-excel': {
    id: 'pdf-to-excel',
    category: 'pdf',
    badge: 'Convert',
    title: 'PDF to Excel',
    subtitle: 'Pull data straight from PDFs into Excel spreadsheets in seconds.',
    description: 'Extract tables and structured numerical data from PDFs into XLSX spreadsheets.',
    iconName: 'FileText',
    seoKeyword: 'convert pdf to excel online free',
    metaTitle: 'Free PDF to Excel Converter — PDF to XLSX | BrowserKit Studio',
    metaDescription: 'Extract tables straight from PDF files into Excel spreadsheets in seconds.',
    faqs: [{ question: 'Does table structure transfer?', answer: 'Yes, table rows and columns are aligned into Excel cells.' }],
  },
  'word-to-pdf': {
    id: 'word-to-pdf',
    category: 'pdf',
    badge: 'Convert',
    title: 'Word to PDF',
    subtitle: 'Make DOC and DOCX files easy to read by converting them to PDF.',
    description: 'Convert Microsoft Word documents into read-only PDF files with accurate formatting.',
    iconName: 'FilePlus',
    seoKeyword: 'convert word to pdf online free',
    metaTitle: 'Free Word to PDF Converter — DOCX to PDF | BrowserKit Studio',
    metaDescription: 'Convert Word DOC and DOCX files to PDF online for free.',
    faqs: [{ question: 'Is DOCX supported?', answer: 'Yes, both legacy DOC and modern DOCX formats are supported.' }],
  },
  'ppt-to-pdf': {
    id: 'ppt-to-pdf',
    category: 'pdf',
    badge: 'Convert',
    title: 'PowerPoint to PDF',
    subtitle: 'Make PPT and PPTX slideshows easy to view by converting to PDF.',
    description: 'Convert presentation slide decks into portable PDF documents.',
    iconName: 'FilePlus',
    seoKeyword: 'convert powerpoint to pdf free',
    metaTitle: 'Free PowerPoint to PDF Converter — PPT to PDF | BrowserKit Studio',
    metaDescription: 'Convert PPT and PPTX presentation slides to PDF online for free.',
    faqs: [{ question: 'Can I view on mobile?', answer: 'PDFs generated can be viewed on any mobile device or browser.' }],
  },
  'excel-to-pdf': {
    id: 'excel-to-pdf',
    category: 'pdf',
    badge: 'Convert',
    title: 'Excel to PDF',
    subtitle: 'Make EXCEL spreadsheets easy to read by converting to PDF.',
    description: 'Convert XLS and XLSX spreadsheets into clean formatted PDF sheets.',
    iconName: 'FilePlus',
    seoKeyword: 'convert excel to pdf online free',
    metaTitle: 'Free Excel to PDF Converter — XLSX to PDF | BrowserKit Studio',
    metaDescription: 'Convert Excel spreadsheets to PDF documents online for free.',
    faqs: [{ question: 'Are print bounds respected?', answer: 'Yes, table margins and print bounds are formatted nicely.' }],
  },
  'pdf-editor': {
    id: 'pdf-editor',
    category: 'pdf',
    badge: 'Popular',
    title: 'Edit PDF',
    subtitle: 'Add text, images, shapes or freehand annotations to a PDF document.',
    description: 'Edit PDF size, font, and color of added content directly inside your browser.',
    iconName: 'Edit3',
    seoKeyword: 'edit pdf online free no signup',
    metaTitle: 'Free PDF Editor Online — Add Text & Annotations | BrowserKit Studio',
    metaDescription: 'Edit PDF documents online for free. Add text, drawings, and shapes without software.',
    faqs: [{ question: 'Is software installation required?', answer: 'No, runs 100% inside your web browser.' }],
  },
  'pdf-to-jpg': {
    id: 'pdf-to-jpg',
    category: 'pdf',
    badge: 'Popular',
    title: 'PDF to JPG',
    subtitle: 'Convert each PDF page into a JPG or extract images contained in a PDF.',
    description: 'Render PDF pages into high-resolution JPG photos or extract embedded images.',
    iconName: 'Image',
    seoKeyword: 'convert pdf to jpg images online',
    metaTitle: 'Free PDF to JPG Converter Online | BrowserKit Studio',
    metaDescription: 'Convert PDF pages into high quality JPG images online for free.',
    faqs: [{ question: 'What is the image resolution?', answer: 'Export high-DPI 300 DPI image renders.' }],
  },
  'images-to-pdf': {
    id: 'images-to-pdf',
    category: 'pdf',
    badge: 'Popular',
    title: 'JPG to PDF',
    subtitle: 'Convert JPG images to PDF in seconds. Easily adjust orientation & margins.',
    description: 'Convert JPG, PNG, and WebP photos into single or multi-page PDF documents.',
    iconName: 'FilePlus',
    seoKeyword: 'convert jpg to pdf online free',
    metaTitle: 'Free JPG to PDF Converter — Images to PDF | BrowserKit Studio',
    metaDescription: 'Convert JPG images to PDF in seconds with custom orientation and page margins.',
    faqs: [{ question: 'Can I combine multiple photos?', answer: 'Yes, arrange photos into a multi-page PDF document.' }],
  },
  'pdf-signer': {
    id: 'pdf-signer',
    category: 'pdf',
    badge: 'Sign',
    title: 'Sign PDF',
    subtitle: 'Sign yourself or request electronic signatures from others.',
    description: 'Draw e-signatures, upload signature stamps, or type legal signature text onto PDF pages.',
    iconName: 'PenTool',
    seoKeyword: 'sign pdf online free e-signature',
    metaTitle: 'Free PDF Signer Online — Add Electronic Signature | BrowserKit Studio',
    metaDescription: 'Sign PDF documents online for free. Draw e-signatures or add signature text 100% locally.',
    faqs: [{ question: 'Is the e-signature legally binding?', answer: 'Yes, electronic signature stamps are applied to document pages.' }],
  },
  'pdf-watermark': {
    id: 'pdf-watermark',
    category: 'pdf',
    badge: 'PDF Suite',
    title: 'Watermark PDF',
    subtitle: 'Stamp an image or text over your PDF in seconds.',
    description: 'Choose typography, transparency, angle, and position to watermark PDF pages.',
    iconName: 'Stamp',
    seoKeyword: 'add watermark to pdf online free',
    metaTitle: 'Free PDF Watermark Tool — Stamp Text & Logos | BrowserKit Studio',
    metaDescription: 'Add text or image watermarks over PDF documents online for free.',
    faqs: [{ question: 'Can I control opacity?', answer: 'Yes, adjust watermark opacity and rotation angle.' }],
  },
  'pdf-rotator': {
    id: 'pdf-rotator',
    category: 'pdf',
    badge: 'PDF Suite',
    title: 'Rotate PDF',
    subtitle: 'Rotate your PDFs the way you need them. Rotate multiple PDFs at once.',
    description: 'Change PDF page orientation to portrait or landscape with 90°, 180°, or 270° rotation.',
    iconName: 'RotateCw',
    seoKeyword: 'rotate pdf pages online free',
    metaTitle: 'Free PDF Rotator Online — Rotate PDF Pages | BrowserKit Studio',
    metaDescription: 'Rotate PDF pages online for free. Rotate individual or all pages permanently.',
    faqs: [{ question: 'Does rotation save permanently?', answer: 'Yes, page rotation angles are saved directly to the exported PDF.' }],
  },
  'html-to-pdf': {
    id: 'html-to-pdf',
    category: 'pdf',
    badge: 'Convert',
    title: 'HTML to PDF',
    subtitle: 'Convert webpages in HTML to PDF with a single click.',
    description: 'Copy and paste webpage HTML markup or URLs to convert them into readable PDF documents.',
    iconName: 'FileCode',
    seoKeyword: 'convert html to pdf online free',
    metaTitle: 'Free HTML to PDF Converter Online | BrowserKit Studio',
    metaDescription: 'Convert web pages and HTML markup to PDF documents online for free.',
    faqs: [{ question: 'Are CSS styles rendered?', answer: 'Yes, modern layout styles and web fonts are rendered cleanly.' }],
  },
  'pdf-password-remover': {
    id: 'pdf-password-remover',
    category: 'pdf',
    badge: 'Security',
    title: 'Unlock PDF',
    subtitle: 'Remove PDF password security, giving freedom to use your PDFs as you want.',
    description: 'Unlock password-protected PDFs and strip printing, editing, and copying restrictions 100% locally.',
    iconName: 'Unlock',
    seoKeyword: 'remove pdf password online free',
    metaTitle: 'Free PDF Password Remover & Unlocker Online | BrowserKit Studio',
    metaDescription: 'Remove passwords and owner restrictions from PDF files online for free.',
    faqs: [{ question: 'Is my password safe?', answer: 'Yes, decryption happens 100% in your local browser RAM.' }],
  },
  'pdf-protector': {
    id: 'pdf-protector',
    category: 'pdf',
    badge: 'Security',
    title: 'Protect PDF',
    subtitle: 'Protect PDF files with a password. Encrypt PDF documents.',
    description: 'Add password encryption to prevent unauthorized opening, editing, or copying of PDF files.',
    iconName: 'Lock',
    seoKeyword: 'password protect pdf file online free',
    metaTitle: 'Free Protect PDF Online — Add Password Encryption | BrowserKit Studio',
    metaDescription: 'Password protect PDF documents online for free. AES encryption with zero server uploads.',
    faqs: [{ question: 'What encryption level is used?', answer: 'Standard AES 128/256-bit password protection.' }],
  },
  'pdf-organizer': {
    id: 'pdf-organizer',
    category: 'pdf',
    badge: 'PDF Suite',
    title: 'Organize PDF',
    subtitle: 'Sort pages of your PDF file however you like. Delete or add PDF pages.',
    description: 'Reorder PDF thumbnails, delete unwanted pages, or insert new pages into existing PDF documents.',
    iconName: 'Layers',
    seoKeyword: 'organize pdf pages reorder delete',
    metaTitle: 'Free Organize PDF Online — Reorder & Delete Pages | BrowserKit Studio',
    metaDescription: 'Sort, reorder, delete, or add PDF pages online for free.',
    faqs: [{ question: 'Can I delete specific pages?', answer: 'Yes, select any thumbnail to delete or move.' }],
  },
  'pdf-to-pdfa': {
    id: 'pdf-to-pdfa',
    category: 'pdf',
    badge: 'Archive',
    title: 'PDF to PDF/A',
    subtitle: 'Transform your PDF to PDF/A ISO-standardized version for long-term archiving.',
    description: 'Preserve document formatting and embed fonts for long-term legal digital archiving compliance.',
    iconName: 'FileCheck',
    seoKeyword: 'convert pdf to pdfa online free',
    metaTitle: 'Free PDF to PDF/A Converter — Archival Standard | BrowserKit Studio',
    metaDescription: 'Convert PDF documents to ISO-standardized PDF/A format for long-term digital archiving.',
    faqs: [{ question: 'What is PDF/A?', answer: 'ISO-standardized format ensuring documents open identically in the future.' }],
  },
  'pdf-repair': {
    id: 'pdf-repair',
    category: 'pdf',
    badge: 'Utility',
    title: 'Repair PDF',
    subtitle: 'Repair a damaged PDF and recover data from corrupt PDF files.',
    description: 'Fix corrupt page trees and rebuild invalid PDF cross-reference tables automatically.',
    iconName: 'Wand2',
    seoKeyword: 'repair damaged corrupt pdf file online',
    metaTitle: 'Free PDF Repair Tool — Fix Corrupted PDFs | BrowserKit Studio',
    metaDescription: 'Repair damaged or corrupt PDF documents online for free.',
    faqs: [{ question: 'Can it recover unreadable pages?', answer: 'Yes, reconstructs damaged stream objects.' }],
  },
  'pdf-page-numbers': {
    id: 'pdf-page-numbers',
    category: 'pdf',
    badge: 'PDF Suite',
    title: 'Page Numbers',
    subtitle: 'Add page numbers into PDFs with ease. Choose positions & typography.',
    description: 'Stamp customizable page numbers (Page 1 of N) onto header or footer sections of PDF pages.',
    iconName: 'Hash',
    seoKeyword: 'add page numbers to pdf online free',
    metaTitle: 'Free PDF Page Numbering Tool — Add Page Numbers | BrowserKit Studio',
    metaDescription: 'Add customizable page numbers to PDF documents online for free.',
    faqs: [{ question: 'Can I customize position?', answer: 'Yes, place numbers at top-right, bottom-center, or bottom-right.' }],
  },
  'pdf-ocr': {
    id: 'pdf-ocr',
    category: 'pdf',
    badge: 'New',
    title: 'OCR PDF',
    subtitle: 'Convert scanned PDF into searchable and selectable documents.',
    description: 'Extract text overlays from scanned image pages to enable copying and searching in PDF readers.',
    iconName: 'Search',
    seoKeyword: 'ocr pdf online free make text searchable',
    metaTitle: 'Free OCR PDF Online — Searchable PDF Text Generator | BrowserKit Studio',
    metaDescription: 'Convert scanned PDFs into searchable text documents online for free.',
    faqs: [{ question: 'Is OCR accurate?', answer: 'High accuracy optical character recognition engine.' }],
  },
  'pdf-compare': {
    id: 'pdf-compare',
    category: 'pdf',
    badge: 'New',
    title: 'Compare PDF',
    subtitle: 'Show a side-by-side document comparison and easily spot changes.',
    description: 'Compare two versions of a PDF document to highlight text, layout, and image changes.',
    iconName: 'Eye',
    seoKeyword: 'compare two pdf documents online side by side',
    metaTitle: 'Free PDF Comparison Tool — Compare PDF Files | BrowserKit Studio',
    metaDescription: 'Compare two PDF document versions side-by-side online for free.',
    faqs: [{ question: 'How are differences shown?', answer: 'Differences are highlighted side-by-side in real-time.' }],
  },
  'pdf-redact': {
    id: 'pdf-redact',
    category: 'pdf',
    badge: 'Security',
    title: 'Redact PDF',
    subtitle: 'Redact text and graphics to permanently remove sensitive information.',
    description: 'Permanently blackout credit card numbers, SSNs, and personal details from PDF documents.',
    iconName: 'ShieldAlert',
    seoKeyword: 'redact pdf text permanently blackout',
    metaTitle: 'Free PDF Redaction Tool — Blackout Sensitive PDF Text | BrowserKit Studio',
    metaDescription: 'Redact and permanently blackout sensitive text from PDF documents online for free.',
    faqs: [{ question: 'Is redaction permanent?', answer: 'Yes, underlying vector text and streams are completely removed.' }],
  },
  'pdf-cropper': {
    id: 'pdf-cropper',
    category: 'pdf',
    badge: 'PDF Suite',
    title: 'Crop PDF',
    subtitle: 'Crop margins of PDF documents or select specific areas.',
    description: 'Trim white margins or crop specific rectangular bounds on PDF document pages.',
    iconName: 'Crop',
    seoKeyword: 'crop pdf margins online free',
    metaTitle: 'Free PDF Cropper Online — Crop PDF Margins | BrowserKit Studio',
    metaDescription: 'Crop PDF margins and adjust document bounding boxes online for free.',
    faqs: [{ question: 'Can I crop all pages at once?', answer: 'Yes, apply margin crop settings to one page or all pages.' }],
  },
  'pdf-forms': {
    id: 'pdf-forms',
    category: 'pdf',
    badge: 'New',
    title: 'PDF Forms',
    subtitle: 'Detect form fields automatically, create interactive fillable PDFs.',
    description: 'Fill out interactive PDF forms, check boxes, select radio buttons, and add text fields.',
    iconName: 'CheckCircle',
    seoKeyword: 'fill pdf form online free fillable pdf',
    metaTitle: 'Free Interactive PDF Form Filler & Builder | BrowserKit Studio',
    metaDescription: 'Fill out interactive PDF forms online for free. Add text fields and checkboxes.',
    faqs: [{ question: 'Can I save filled forms?', answer: 'Yes, save filled interactive PDF forms directly to disk.' }],
  },
  'pdf-ai-summarizer': {
    id: 'pdf-ai-summarizer',
    category: 'pdf',
    badge: 'AI Powered',
    title: 'AI PDF Summarizer',
    subtitle: 'Quickly generate concise summaries from articles, paragraphs & essays.',
    description: 'Extract executive summaries, key bullet points, and main highlights from multi-page PDFs using client-side AI.',
    iconName: 'Sparkles',
    seoKeyword: 'ai pdf summarizer online free',
    metaTitle: 'Free AI PDF Summarizer — Extract Key Points | BrowserKit Studio',
    metaDescription: 'Generate concise executive summaries from PDF articles and essays online for free.',
    faqs: [{ question: 'Is my document sent to external AI servers?', answer: 'No, processing occurs 100% locally.' }],
  },
  'pdf-translate': {
    id: 'pdf-translate',
    category: 'pdf',
    badge: 'AI Powered',
    title: 'Translate PDF',
    subtitle: 'Easily translate PDF files powered by AI while keeping layout intact.',
    description: 'Translate PDF documents into Spanish, French, German, Hindi, and more while preserving visual layout.',
    iconName: 'Languages',
    seoKeyword: 'translate pdf document online free',
    metaTitle: 'Free AI PDF Translator — Translate PDF Documents | BrowserKit Studio',
    metaDescription: 'Translate PDF documents online for free while keeping fonts and layout intact.',
    faqs: [{ question: 'Which languages are supported?', answer: 'Supports over 50+ international languages.' }],
  },
  'pdf-to-markdown': {
    id: 'pdf-to-markdown',
    category: 'pdf',
    badge: 'Developer',
    title: 'PDF to Markdown',
    subtitle: 'Easily turn PDFs into structured Markdown documents.',
    description: 'Extract headings, paragraphs, code blocks, and tables into clean Markdown (.md) markup.',
    iconName: 'FileCode',
    seoKeyword: 'convert pdf to markdown md online',
    metaTitle: 'Free PDF to Markdown Converter — PDF to MD | BrowserKit Studio',
    metaDescription: 'Turn PDF files into clean Markdown documents online for free.',
    faqs: [{ question: 'Can I export .md files?', answer: 'Yes, download formatted .md markdown documents with 1 click.' }],
  },

  // Archive & Security
  'zip-archiver': {
    id: 'zip-archiver',
    category: 'zip',
    badge: 'ZIP Suite',
    title: 'ZIP Creator & File Archiver',
    subtitle: 'Compress images, documents, and videos into a downloadable .zip package.',
    description: 'Combine files into a compressed .zip archive directly in your browser.',
    iconName: 'Archive',
    seoKeyword: 'create zip file online free',
    metaTitle: 'Free ZIP Creator Online | BrowserKit Studio',
    metaDescription: 'Create .zip compressed archives online for free with zero server uploads.',
    faqs: [{ question: 'Size limit?', answer: 'Create archives up to hundreds of megabytes in browser RAM.' }],
  },
  'zip-extractor': {
    id: 'zip-extractor',
    category: 'zip',
    badge: 'ZIP Suite',
    title: 'ZIP Extractor & Archive Viewer',
    subtitle: 'Inspect and extract files from .zip archives without uploading.',
    description: 'Drop any .zip archive to view contents, file sizes, and extract individual files.',
    iconName: 'FolderArchive',
    seoKeyword: 'extract zip file online free',
    metaTitle: 'Free ZIP Extractor Online | BrowserKit Studio',
    metaDescription: 'Unzip and extract files from .zip archives online for free.',
    faqs: [{ question: 'Inspect zip?', answer: 'Yes, preview file list before extracting.' }],
  },
  'zip-password-remover': {
    id: 'zip-password-remover',
    category: 'zip',
    badge: 'Security',
    title: 'ZIP Password Remover',
    subtitle: 'Unlock password-protected ZIP archives and extract all contents.',
    description: 'Unlock encrypted ZIP archives and extract all contained files 100% locally.',
    iconName: 'Unlock',
    seoKeyword: 'unlock password protected zip file online',
    metaTitle: 'Free ZIP Password Remover & Unlocker Online | BrowserKit Studio',
    metaDescription: 'Unlock password-protected ZIP archives online for free.',
    faqs: [{ question: 'How it works?', answer: 'Decrypts zip archives locally inside browser RAM.' }],
  },
  'audio-tools': {
    id: 'audio-tools',
    category: 'audio',
    badge: 'Audio',
    title: 'Audio Converter & Sound Extractor',
    subtitle: 'Convert audio formats or extract high quality audio tracks from video files.',
    description: 'Convert audio recordings between MP3, WAV, OGG, and extract audio from MP4 videos.',
    iconName: 'Music',
    seoKeyword: 'extract audio from mp4 free',
    metaTitle: 'Free Audio Converter & Video Audio Extractor | BrowserKit Studio',
    metaDescription: 'Extract audio from video and convert audio formats online for free.',
    faqs: [{ question: 'Which formats?', answer: 'MP3, WAV, OGG, WebM, AAC, and M4A.' }],
  },
  'svg-optimizer': {
    id: 'svg-optimizer',
    category: 'image',
    badge: 'Developer',
    title: 'SVG Cleaner & Minifier',
    subtitle: 'Minify raw SVG markup, strip editor metadata, or convert SVG to PNG.',
    description: 'Clean up vector graphics created in Figma, Illustrator, or Inkscape.',
    iconName: 'Code',
    seoKeyword: 'svg optimizer minifier online',
    metaTitle: 'Free SVG Cleaner, Minifier & PNG Rasterizer | BrowserKit Studio',
    metaDescription: 'Optimize and minify SVG markup online for free.',
    faqs: [{ question: 'Breaks styling?', answer: 'No, strips only redundant comments and unused tags.' }],
  },
  'file-encryptor': {
    id: 'file-encryptor',
    category: 'zip',
    badge: 'Security',
    title: 'Client-Side File Encryptor (AES-256 Vault)',
    subtitle: 'Encrypt photos, videos, PDFs, and documents with military-grade password vaulting.',
    description: 'Protect sensitive files using AES-256-GCM encryption with PBKDF2 password derivation.',
    iconName: 'Lock',
    seoKeyword: 'password encrypt file online free',
    metaTitle: 'Free File Encryptor — AES-256 Password Protect | BrowserKit Studio',
    metaDescription: 'Encrypt photos, PDFs, documents, and ZIP files with password protection online for free.',
    faqs: [{ question: 'Unbreakable?', answer: 'Yes, AES-256 is mathematically unbreakable without password.' }],
  },
};

export function generateSitemapXML(baseUrl = 'https://browserkit.co.in'): string {
  const routes = [
    '',
    'pdf-tools',
    'image-tools',
    'video-tools',
    'zip-tools',
    'heic-to-jpg',
    'convert-heic-to-jpg-mac',
    'compress-image-under-100kb',
    'compress-image-to-20kb',
    'passport-photo-maker',
    'passport-photo-crop-2x2',
    'add-name-and-dob-on-photo',
    'resize-signature-300-dpi',
    'merge-photo-and-signature',
    'png-to-webp',
    'png-to-ico-favicon',
    'remove-pdf-password',
    'unlock-pdf-online',
    'compress-pdf-to-200kb',
    'pdf-merger',
    'pdf-splitter',
    'pdf-to-word',
    'pdf-to-jpg',
    'images-to-pdf',
    'pdf-signer',
    'resize-video-aspect-ratio-9-16',
    'convert-video-to-mp3-320kbps',
    'audio-cutter-ringtone-maker',
    'social-video-downloader',
    'social-audio-extractor',
    'thumbnail-grabber',
    'video-format-swapper',
    'gif-maker',
    'trim-video-without-watermark',
    'video-trimmer',
    'unlock-zip-file',
    'remove-zip-password',
    'guides',
    'privacy',
    'terms',
  ];

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${routes
  .map(
    (r) => `  <url>
    <loc>${baseUrl}/${r}</loc>
    <lastmod>2026-08-09</lastmod>
    <changefreq>weekly</changefreq>
    <priority>${r === '' ? '1.0' : r.endsWith('-tools') ? '0.95' : '0.9'}</priority>
  </url>`
  )
  .join('\n')}
</urlset>`;
}

export function generateRobotsTxt(domain?: any): string {
  return `User-agent: *\nAllow: /\n\nSitemap: https://browserkit.co.in/sitemap.xml`;
}
